version: "3.9"
services:
  postgres:
    container_name: mypostgres
    image: postgres:14.5
    restart: unless-stopped
    hostname: db
    volumes:
      - ./db/tables.sql:/docker-entrypoint-initdb.d/dbinit.sql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
    networks:
      - smnet
  app:
    build: ./
    ports:
      - "8000:8080"
    depends_on:
       postgres:
         condition: service_started
    environment:
       DB_PASSWORD: 'qwerty'
       SERVER_PORT: 8080
       CONNECTIONSTRING: "postgres://db:5432"
    networks:
      - smnet
networks:
  smnet:
    driver: bridge

