version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: unless-stopped
    hostname: postgres
    volumes:
      - .pkg/db/tables.sql:/docker-entrypoint-initdb.d/dbinit.sql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5433:5432"
    healthcheck:
       test: "exit 0"
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
       postgres:
         condition: service_healthy
    environment:
       DB_PASSWORD: 'qwerty'
       SERVER_PORT: 8080

